<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Component</name>
   <tag></tag>
   <elementGuidId>a2fd8851-c1f4-4dc4-bfee-62c865fd0f2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='Component']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;Component&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>623bc82c-ad9a-4550-9c15-6632c61fe1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hvr-bounce-to-right master-nav classForMenu</value>
      <webElementGuid>2c45b942-3dd6-44b7-be61-bc2f998e47ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>0f6837f1-6990-4f73-8f44-474679be6e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Component</value>
      <webElementGuid>ac12535e-5002-4106-81da-44258468351b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Component</value>
      <webElementGuid>19cc0a8f-917e-4eeb-ae4b-cc99ca27bacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-wrapper&quot;)/ul[@class=&quot;sidebar-nav&quot;]/li[8]/a[@class=&quot;hvr-bounce-to-right master-nav classForMenu&quot;]</value>
      <webElementGuid>3e00630c-8440-440d-bc60-d73e320ca268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='Component']</value>
      <webElementGuid>b7de6761-6904-4fd1-87b2-dd3ac9a315fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-wrapper']/ul/li[8]/a</value>
      <webElementGuid>fbcf67ab-f42f-475d-a552-76b73c9a45c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Component')]</value>
      <webElementGuid>dead5462-197f-4ff1-99fa-ece89d5128f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[8]</value>
      <webElementGuid>3d1c7655-cea4-41cd-ae78-cf9a1451ad7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>23fce995-eed3-438e-bc60-633f6d3572bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @name = 'Component' and (text() = 'Component' or . = 'Component')]</value>
      <webElementGuid>9445cabd-36fb-4264-8610-d1cc1b5b8711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
