<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Medical Claim</name>
   <tag></tag>
   <elementGuidId>28f125f7-75b0-4b9c-8493-28ed2bce44cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='Medical Claim']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;Medical Claim&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b4d63d4-4be6-4104-a951-9627a3566eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>classForFunction sub-nav</value>
      <webElementGuid>e5623a2c-f4e6-40b5-b6ea-2b0576cef140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Medical Claim</value>
      <webElementGuid>794c4877-c593-42ae-b615-e62c0cbd184b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>195</value>
      <webElementGuid>76275fa9-9580-4d44-b453-a66f8d32eb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>319b0b1c-0032-4e8c-bf0d-80cdcc947ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-begin</name>
      <type>Main</type>
      <value>RemovePrevData</value>
      <webElementGuid>ab94083b-09b1-48ad-9edd-c20f53881bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>fb299e39-af8d-48a6-8107-ba558c05b128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#result</value>
      <webElementGuid>ecd20dc6-fd50-49f0-89cc-184b625f0341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-loading</name>
      <type>Main</type>
      <value>#Loading</value>
      <webElementGuid>897054ff-1b48-47bd-9f39-11f65bd665fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Application/Component/MedicalClaim</value>
      <webElementGuid>28b62741-d67c-423b-8487-bcb368075fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medical Claim</value>
      <webElementGuid>d545fefb-8409-4ea4-b216-172234ef104b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-wrapper&quot;)/ul[@class=&quot;sidebar-nav&quot;]/li[8]/ul[@class=&quot;master-subnav&quot;]/li[2]/a[@class=&quot;classForFunction sub-nav&quot;]</value>
      <webElementGuid>f4269c1e-06d2-4d51-bd57-da6227d32ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='Medical Claim']</value>
      <webElementGuid>1c303a9f-e3b5-4d0f-807d-338fa4ee9270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-wrapper']/ul/li[8]/ul/li[2]/a</value>
      <webElementGuid>2f82306a-e4d7-4156-9481-53c8cd0fc725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Medical Claim')]</value>
      <webElementGuid>01809463-b64b-4d50-a12b-a4feb13ebc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Application/Component/MedicalClaim')]</value>
      <webElementGuid>ac9bd9dc-4674-46eb-8744-70ddba5ce5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[2]/a</value>
      <webElementGuid>8fcc868d-9736-48a8-9516-cd269c604e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Medical Claim' and @href = '/Application/Component/MedicalClaim' and (text() = 'Medical Claim' or . = 'Medical Claim')]</value>
      <webElementGuid>a2fb8ef4-3cf7-4d46-8453-32ec507d8f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
